micronaut:
  application:
    name: micronaut-security-cookie-graal
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
    token:
      jwt:
        enabled: true
        bearer:
          enabled: false
        cookie:
          enabled: true
          loginFailureTargetUrl: /login/authFailed
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
