micronaut:
  application:
    name: micronaut-security-cookie-graal
  security:
    authentication: cookie
    redirect:
      login-failure: /login/authFailed
    token:
      jwt:
        cookie:
          cookie-secure: false
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
