micronaut:
  application:
    name: micronaut-security-cookie-graal
  security:
    redirect:
      login-failure: /login/authFailed
    token:
      jwt:
        bearer:
          enabled: false
        cookie:
          enabled: true
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
    login-handler: cookie
