micronaut:
  application:
    name: micronaut-security-cookie-graal
  security:
    token:
      jwt:
        bearer:
          enabled: false
        cookie:
          enabled: true
          loginFailureTargetUrl: /login/authFailed
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
    login-handler: cookie
